# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Release

on:
  push:
    tags: ["*"]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Publish
      run: dotnet publish -c Release --no-restore
    - name: Package
      working-directory: bin/Release/net8.0/publish
      run: zip nahkd123.HoverToPressure.zip metadata.json nahkd123.HoverToPressure.dll
    - uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        prerelease: false
        draft: false
        files: bin/Release/net8.0/publish/nahkd123.HoverToPressure.zip
